# nginx 전용 서버
services:

  nginx:
    image: nginx:1.27-alpine
    container_name: rezy-nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro    # 읽기 전용으로 마운트
    restart: unless-stopped